-- ============================================================
-- SISTEM ADMINISTRASI SURAT ORGANISASI
-- Supabase / PostgreSQL
-- Jalankan seluruh script ini di SQL Editor Supabase.
-- Setelah itu buat bucket Storage bernama: surat-files (PRIVATE)
-- ============================================================

create extension if not exists pgcrypto;

-- ---------- profiles ----------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nama text not null default '',
  username text unique,
  email text,
  jabatan text,
  role text not null default 'Pengurus' check (role in ('Admin','Sekretaris','Pengurus')),
  status text not null default 'Aktif' check (status in ('Aktif','Nonaktif')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- helper roles ----------
-- Dibuat setelah tabel profiles karena fungsi-fungsi ini membacanya.
create or replace function public.current_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select role from public.profiles where id = auth.uid()), 'Pengurus');
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_role() in ('Admin','Sekretaris');
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.current_role() = 'Admin';
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id,nama,username,email,jabatan,role,status)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nama', split_part(coalesce(new.email,''),'@',1)),
    nullif(new.raw_user_meta_data->>'username',''),
    new.email,
    nullif(new.raw_user_meta_data->>'jabatan',''),
    'Pengurus',
    'Aktif'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- ---------- organisasi ----------
create table if not exists public.organisasi (
  id bigint generated by default as identity primary key,
  nama_organisasi text not null default 'Organisasi Mahasiswa',
  logo text,
  alamat text,
  email text,
  telepon text,
  nama_ketua text,
  nama_sekretaris text,
  tahun_kepengurusan text,
  nomor_kontak text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- surat masuk ----------
create table if not exists public.surat_masuk (
  id bigint generated by default as identity primary key,
  nomor_surat text not null,
  tanggal_surat date not null,
  tanggal_diterima date not null,
  asal_surat text not null,
  alamat_pengirim text,
  perihal text not null,
  tujuan text,
  ringkasan text,
  sifat text not null default 'Biasa' check (sifat in ('Biasa','Penting','Segera','Rahasia')),
  lampiran text,
  file_surat text,
  file_surat_nama text,
  file_surat_ukuran bigint,
  status text not null default 'Baru Diterima',
  catatan text,
  ditandai_penting boolean not null default false,
  created_by uuid references public.profiles(id) on delete set null,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- disposisi ----------
create table if not exists public.disposisi (
  id bigint generated by default as identity primary key,
  surat_masuk_id bigint not null references public.surat_masuk(id) on delete cascade,
  tanggal_disposisi date not null default current_date,
  dari_user_id uuid references public.profiles(id) on delete set null,
  kepada_user_id uuid not null references public.profiles(id) on delete restrict,
  instruksi text not null,
  batas_waktu date,
  catatan text,
  catatan_tindak_lanjut text,
  status text not null default 'Belum Diproses' check (status in ('Belum Diproses','Sedang Diproses','Selesai')),
  tanggal_selesai timestamptz,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- surat keluar ----------
create table if not exists public.surat_keluar (
  id bigint generated by default as identity primary key,
  nomor_surat text,
  tanggal_surat date not null,
  jenis_surat text not null default 'Surat lainnya',
  pengaju text not null,
  tujuan text not null,
  alamat_tujuan text,
  perihal text not null,
  ringkasan text,
  sifat text not null default 'Biasa' check (sifat in ('Biasa','Penting','Segera','Rahasia')),
  penandatangan text,
  jabatan_penandatangan text,
  file_draft text,
  file_draft_nama text,
  file_draft_ukuran bigint,
  file_final text,
  file_final_nama text,
  file_final_ukuran bigint,
  status text not null default 'Permintaan Baru',
  catatan text,
  catatan_revisi text,
  tanggal_dikirim date,
  metode_pengiriman text,
  bukti_pengiriman text,
  bukti_pengiriman_nama text,
  created_by uuid references public.profiles(id) on delete set null,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- workflow ----------
create table if not exists public.surat_workflow (
  id bigint generated by default as identity primary key,
  surat_id bigint not null,
  jenis_surat text not null check (jenis_surat in ('masuk','keluar')),
  status_sebelumnya text,
  status_baru text not null,
  catatan text,
  user_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

-- ---------- activity logs ----------
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  aktivitas text not null,
  tipe_data text,
  data_id bigint,
  created_at timestamptz not null default now()
);

-- ---------- nomor surat ----------
create table if not exists public.nomor_surat (
  id bigint generated by default as identity primary key,
  tahun integer not null unique,
  nomor_terakhir integer not null default 0,
  format_nomor text not null default '{nomor}/ORG/SEK/{bulan_romawi}/{tahun}',
  kode_organisasi text not null default 'ORG',
  kode_sekretariat text not null default 'SEK',
  updated_at timestamptz not null default now()
);

-- ---------- updated_at helper ----------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare t text;
begin
  foreach t in array array['profiles','organisasi','surat_masuk','disposisi','surat_keluar','nomor_surat'] loop
    execute format('drop trigger if exists touch_updated_at on public.%I',t);
    execute format('create trigger touch_updated_at before update on public.%I for each row execute function public.touch_updated_at()',t);
  end loop;
end $$;

-- ---------- nomor otomatis ----------
create or replace function public.ambil_nomor_surat(p_tahun integer, p_bulan integer)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_last integer;
  v_next integer;
  v_fmt text;
  v_kode_org text;
  v_kode_sek text;
  v_romawi text;
  v_result text;
begin
  insert into public.nomor_surat(tahun, nomor_terakhir)
  values (p_tahun,0)
  on conflict (tahun) do nothing;

  select nomor_terakhir, format_nomor, kode_organisasi, kode_sekretariat
    into v_last, v_fmt, v_kode_org, v_kode_sek
  from public.nomor_surat where tahun=p_tahun for update;

  v_next := v_last + 1;
  update public.nomor_surat set nomor_terakhir=v_next where tahun=p_tahun;

  v_romawi := case p_bulan
    when 1 then 'I' when 2 then 'II' when 3 then 'III' when 4 then 'IV'
    when 5 then 'V' when 6 then 'VI' when 7 then 'VII' when 8 then 'VIII'
    when 9 then 'IX' when 10 then 'X' when 11 then 'XI' when 12 then 'XII'
    else to_char(p_bulan,'FM00') end;

  v_result := replace(v_fmt,'{nomor}',lpad(v_next::text,3,'0'));
  v_result := replace(v_result,'{bulan}',lpad(p_bulan::text,2,'0'));
  v_result := replace(v_result,'{bulan_romawi}',v_romawi);
  v_result := replace(v_result,'{tahun}',p_tahun::text);
  v_result := replace(v_result,'{kode_organisasi}',coalesce(v_kode_org,'ORG'));
  v_result := replace(v_result,'{kode_sekretariat}',coalesce(v_kode_sek,'SEK'));
  return v_result;
end;
$$;
grant execute on function public.ambil_nomor_surat(integer,integer) to authenticated;

-- ---------- indexes ----------
create index if not exists idx_surat_masuk_tanggal on public.surat_masuk(tanggal_diterima desc);
create index if not exists idx_surat_masuk_status on public.surat_masuk(status);
create index if not exists idx_disposisi_kepada on public.disposisi(kepada_user_id,status);
create index if not exists idx_surat_keluar_tanggal on public.surat_keluar(tanggal_surat desc);
create index if not exists idx_surat_keluar_status on public.surat_keluar(status);
create index if not exists idx_workflow_surat on public.surat_workflow(surat_id,jenis_surat,created_at);
create index if not exists idx_activity_created on public.activity_logs(created_at desc);

-- ---------- RLS ----------
alter table public.profiles enable row level security;
alter table public.organisasi enable row level security;
alter table public.surat_masuk enable row level security;
alter table public.disposisi enable row level security;
alter table public.surat_keluar enable row level security;
alter table public.surat_workflow enable row level security;
alter table public.activity_logs enable row level security;
alter table public.nomor_surat enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles for select to authenticated using (true);
drop policy if exists profiles_insert_admin on public.profiles;
create policy profiles_insert_admin on public.profiles for insert to authenticated with check (public.is_admin());
drop policy if exists profiles_update_admin on public.profiles;
create policy profiles_update_admin on public.profiles for update to authenticated using (public.is_admin() or id=auth.uid()) with check (public.is_admin() or id=auth.uid());
drop policy if exists profiles_delete_admin on public.profiles;
create policy profiles_delete_admin on public.profiles for delete to authenticated using (public.is_admin());

drop policy if exists org_select on public.organisasi;
create policy org_select on public.organisasi for select to authenticated using (true);
drop policy if exists org_write_staff on public.organisasi;
create policy org_write_staff on public.organisasi for all to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists masuk_select on public.surat_masuk;
create policy masuk_select on public.surat_masuk for select to authenticated using (
  public.is_staff() or exists (select 1 from public.disposisi d where d.surat_masuk_id=id and d.kepada_user_id=auth.uid() and d.deleted_at is null)
);
drop policy if exists masuk_write_staff on public.surat_masuk;
create policy masuk_write_staff on public.surat_masuk for all to authenticated using (public.is_staff()) with check (public.is_staff());

drop policy if exists disp_select on public.disposisi;
create policy disp_select on public.disposisi for select to authenticated using (public.is_staff() or kepada_user_id=auth.uid() or dari_user_id=auth.uid());
drop policy if exists disp_insert_staff on public.disposisi;
create policy disp_insert_staff on public.disposisi for insert to authenticated with check (public.is_staff());
drop policy if exists disp_update_owner_or_staff on public.disposisi;
create policy disp_update_owner_or_staff on public.disposisi for update to authenticated using (public.is_staff() or kepada_user_id=auth.uid()) with check (public.is_staff() or kepada_user_id=auth.uid());
drop policy if exists disp_delete_staff on public.disposisi;
create policy disp_delete_staff on public.disposisi for delete to authenticated using (public.is_staff());

drop policy if exists keluar_select on public.surat_keluar;
create policy keluar_select on public.surat_keluar for select to authenticated using (public.is_staff() or created_by=auth.uid());
drop policy if exists keluar_insert_staff on public.surat_keluar;
create policy keluar_insert_staff on public.surat_keluar for insert to authenticated with check (public.is_staff());
drop policy if exists keluar_update_staff on public.surat_keluar;
create policy keluar_update_staff on public.surat_keluar for update to authenticated using (public.is_staff()) with check (public.is_staff());
drop policy if exists keluar_delete_staff on public.surat_keluar;
create policy keluar_delete_staff on public.surat_keluar for delete to authenticated using (public.is_staff());

drop policy if exists wf_select on public.surat_workflow;
create policy wf_select on public.surat_workflow for select to authenticated using (true);
drop policy if exists wf_insert_staff on public.surat_workflow;
create policy wf_insert_staff on public.surat_workflow for insert to authenticated with check (public.is_staff());

drop policy if exists activity_insert_auth on public.activity_logs;
create policy activity_insert_auth on public.activity_logs for insert to authenticated with check (user_id=auth.uid());
drop policy if exists activity_select_staff on public.activity_logs;
create policy activity_select_staff on public.activity_logs for select to authenticated using (public.is_staff());

drop policy if exists nomor_select_auth on public.nomor_surat;
create policy nomor_select_auth on public.nomor_surat for select to authenticated using (true);
drop policy if exists nomor_write_admin on public.nomor_surat;
create policy nomor_write_admin on public.nomor_surat for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------- storage ----------
-- Buat bucket private bernama surat-files dari Storage UI sebelum memakai upload.
-- Policy object di bawah memberi akses baca kepada user login, upload kepada staff.
drop policy if exists surat_files_select_auth on storage.objects;
create policy surat_files_select_auth on storage.objects for select to authenticated using (bucket_id='surat-files');
drop policy if exists surat_files_insert_staff on storage.objects;
create policy surat_files_insert_staff on storage.objects for insert to authenticated with check (bucket_id='surat-files' and public.is_staff());
drop policy if exists surat_files_update_staff on storage.objects;
create policy surat_files_update_staff on storage.objects for update to authenticated using (bucket_id='surat-files' and public.is_staff()) with check (bucket_id='surat-files' and public.is_staff());
drop policy if exists surat_files_delete_staff on storage.objects;
create policy surat_files_delete_staff on storage.objects for delete to authenticated using (bucket_id='surat-files' and public.is_staff());

-- ---------- seed organisasi ----------
insert into public.organisasi (nama_organisasi,alamat,email,telepon,nama_ketua,nama_sekretaris,tahun_kepengurusan,nomor_kontak)
select 'UKM Organisasi Mahasiswa','Jl. Pendidikan No. 10, Makassar','sekretariat@organisasi.test','0812-0000-0000','Ketua Organisasi','Sekretaris Organisasi','2026/2027','0812-0000-0000'
where not exists (select 1 from public.organisasi);

insert into public.nomor_surat (tahun,nomor_terakhir,format_nomor,kode_organisasi,kode_sekretariat)
values (extract(year from current_date)::int,15,'{nomor}/ORG/SEK/{bulan_romawi}/{tahun}','ORG','SEK')
on conflict (tahun) do nothing;

-- Catatan akun:
-- Buat akun awal di Authentication > Users dengan email/password.
-- Setelah akun dibuat, trigger otomatis membuat profiles role Pengurus.
-- Ubah role akun pertama menjadi Admin melalui SQL sekali:
-- update public.profiles set role='Admin', jabatan='Administrator' where email='email-anda@contoh.com';
